version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:9.4
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
